<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="BenchmarkDotNet" Version="0.15.8" />
    <PackageVersion Include="BenchmarkDotNet.Annotations" Version="0.15.8" />
    <PackageVersion Include="Polyfill" Version="11.3.0" />
  </ItemGroup>
</Project>
